# Spring Boot Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: socket-app
  template:
    metadata:
      labels:
        app: socket-app
    spec:
      containers:
        - name: socket-app
          image: socket-app
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: "redis-service"
            - name: KAFKA_BOOTSTRAP_SERVERS
              # direct reach the pod with the service name
              value: "kafka-service:9092"

---
apiVersion: v1
kind: Service
metadata:
  name: socket-app-service
spec:
  selector:
    app: socket-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer